### ISSUE TITLE
Make a spinner

### ISSUE THREAD

**Issue by davidgatti** [0x4447/contract.0x4447.com#3]
![screen shot 2018-09-21 at 9 26 10 am](https://user-images.githubusercontent.com/411114/45866471-3b697d00-bd81-11e8-9f44-0c71dec2c81f.png)

On every page, that loads data from DynamoDB, we need by default add a transparent div, with a spinner to show the user that data is being loaded, and remove the over lay once the data is loaded and replaced on the page.

**Important**: add the word `Loading...` bellow the spinner.

**Comment by radiantdinosaurs** [comment]
I wanted to note that I made the loading overlay have an opaque background.

This is because with a transparent or translucent background, the user would see that the webpage is incomplete (e.g., "Hi ," on the homepage). By using an opaque background, we hide the page from the user until all the information is loaded in.

But, let me know if you want me to change it to transparent.
